

C = stimButtonTiling();
 C{1} ='RF/RC/FS/FM/THR/TCKL/ARevcor/THR_TCKL'
% C{6}= 'CFS/CTD/CSPL/MOVING_W/ZWICKER'
% MOVING_W/ZWICKER
% C{7}
% C{7}= 'WAV/QFM/NSAM/HAR/ENH_W/ENH_d'
% C{8   } = 'NPHI/MASK/SUP/ZW/ENH_2T/ENH_FC'
% C{7}=    'WAV/QFM/NSAM/HAR/ENH_W/ENH_d/ENH_dB/MASKING'
C{8} = 'NPHI/MASK/SUP/ZW/ENH_2T/ENH_FC/ENH_durC/MASK_T/MASK_dB'
% 
% C{4} = 'ITD/ILD/MBL/'
stimButtonTiling(C) 

